services:
  - type: web
    name: namma-rytha-backend
    env: node
    plan: free
    buildCommand: npm install --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.20.0
      - key: GOOGLE_CLIENT_ID
        value: 166834385153-oqpgsnhkufrreqeskgor54q7j4tldtin.apps.googleusercontent.com
      - key: MONGO_URI
        sync: false   # Set this in the Render dashboard → Environment tab
